http:
  port: "8081"
 
scheduler:
  expression: "0 00 20 ? * *"

mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "1234"
  database: "employee_details"
  
sf:
  name: "irshad.ahmad@apisero.com"
  password: "apisero@123"
  token: "Iw10fQmpjrvSzOdD3cd1P8ixK"
  
email:
  id: "dummyzoho33@gmail.com"
  password: "@pisero@2020"
  user: "smtp.gmail.com"
  port: "587"